### ISSUE TITLE
Update InterWiki

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pydotorg/backlog#21]
```
1. Add "Python http://www.python.org/" string to InterWiki map
2. Clean up some broken/outdated links around

Python Wiki inherits the page from MoinMoin. MoinMoin inherits from 
http://meatballwiki.org/wiki/InterMapTxt - there is also a note about this 
issue on MoinMoin somewhere.
```

Original issue reported on code.google.com by `techtonik@gmail.com` on 14 Mar 2011 at 10:28

**Comment by techtonik** [comment]
[MediaWiki](https://git.wikimedia.org/blob/mediawiki%2Fcore.git/HEAD/maintenance%2Finterwiki.list) - `[[pythoninfo:SiteImprovements]]`
[MoinMoin](https://moinmo.in/InterWiki) - PythonInfo:SiteImprovements
[Trac](http://trac.edgewall.org/wiki/InterMapTxt) - PythonInfo:SiteImprovements (just added)
